Ajout du build pour android
PapillonApp/docs pull request #11
Opened 2024-12-21 02:51 UTC by Wateir

Basé sur les conseil de Gabriel.

Pour voir le [message de Gabriel](https://discord.com/channels/1014931881906675712/1211823639222296587/1319786563374415903)

2024-12-21 10:06 UTC, Clmnnt requested changes
2 ptites choses a changer mais sinon good

2024-12-21 10:06 UTC, Clmnnt commented on develop/build/pour-android.md
Faut rajouter : "Pour build Papillon pour Android, utilisez ceci" ou autre

2024-12-21 10:06 UTC, Clmnnt commented on develop/build/pour-android.md
> +cd app/build/outputs/apk/release # Et là t'as ton apk !
"t'as ton apk" ???

2024-12-21 15:18 UTC, Wateir commented on develop/build/pour-android.md
> +cd app/build/outputs/apk/release # Et là t'as ton apk !
Ca c’est ce que gabriel avais mis dans son message originel

2024-12-21 19:59 UTC, Clmnnt commented
Un commentaire.

2024-12-21 20:27 UTC, Clmnnt commented on develop/build/pour-android.md
bah non j'ai pas les perms 💀

2024-12-21 20:27 UTC, Clmnnt commented on develop/build/pour-android.md
> +cd app/build/outputs/apk/release # Et là t'as ton apk !
bah okay mais modifie en fonction

2024-12-22 17:31 UTC, Clmnnt approved these changes

2024-12-22 17:34 UTC, Clmnnt commented
@Wateir g modif donc

2025-01-02 19:47 UTC, merged