fix: Mise à jour du lien vers le discord
PapillonApp/docs pull request #40
Opened 2024-03-25 17:19 UTC by oriionn

Bonsoir,
J'ai simplement mis à jour le lien vers le Discord étant de donner que l'ancien lien était invalide.

2024-03-25 17:22 UTC, ecnivtwelve requested changes
http://discord.gg/ywkBZx2jFB existe bel et bien.

2024-03-25 17:23 UTC, Vilerio requested changes
Le lien fonctionne très bien, je comprends pas trop l'objectif là

2024-03-25 17:24 UTC, oriionn commented
Alors spoiler : je viens de me rendre que c'est juste le / qui faisait de la merde pour la doc ptdr

2024-03-25 17:26 UTC, Vilerio commented
y a rien du tout, ça fonctionne bien de mon côté

2024-03-25 17:26 UTC, oriionn commented
Avec le slash (lien actuellement dans la doc)
![image](https://github.com/PapillonApp/docs/assets/38093786/61ab2972-37c4-4a73-ba1b-05209e2fbd93)

Sans le slash (lien actuellement sur le [site officiel](https://oriondev.fr)
![image](https://github.com/PapillonApp/docs/assets/38093786/30b35af0-e06b-451f-adf2-9c622adb0544)

2024-03-25 17:28 UTC, oriionn commented
Donc en résumé : c'est un slash qui foutait la merde ptdr

2024-03-25 17:32 UTC, maelgangloff approved these changes

2024-03-26 15:31 UTC, oriionn commented
donc j'espère que vous avez compris ce que j'ai modifié au final

2024-03-26 15:45 UTC, Vilerio approved these changes

2024-03-26 15:45 UTC, Vilerio commented
@ecnivtwelve tout est bon pour toi ? comme t'avais request change aussi (si oui approuve stp)

2024-04-08 16:52 UTC, Ahhj93 approved these changes

2024-04-12 21:40 UTC, merged