Ajout (ou mise à jour) de la documentation de "Papillon ED Core"
PapillonApp/docs pull request #44
Opened 2024-04-13 15:28 UTC by camarm-dev

Liste des modifications:
- `docs/development/api/ed/papillon.md`; Modification de la documentation: copié-collé de [papillon-ed-core/DOCUMENTATION.md](https://github.com/camarm-dev/papillon-ed-core/blob/dev/DOCUMENTATION.md)
    - Modification des liens relatif en liens vers github
    - Ajout d'un disclaimer Papillon != ED
- `docs/development/ent.md`; Changement de "société Ecoledirecte" vers "société Aplim"

2024-04-14 12:35 UTC, oriionn commented on docs/development/ent.md
> +    EcoleDirecte est une marque déposée de la société [Aplim :octicons-link-external-24:](https://www.ecoledirecte.com/){target='_blank'}. Papillon n'est pas affilié à EcoleDirecte.
Mets le site d'Aplim quand tu parles d'Aplim et pas le site d'EcoleDirecte ;)
https://www.aplim.fr/

2024-04-14 13:06 UTC, oriionn approved these changes
Pour moi, c'est bon 👍

2024-04-14 13:36 UTC, ecnivtwelve approved these changes

2024-04-14 19:31 UTC, Sacha338 requested changes

2024-04-14 19:31 UTC, Sacha338 commented on docs/development/api/ed/papillon.md
> +| get()     | `async (url: string, body: string, params?: string, ignoreErrors: boolean = false) => object`               | Exécute la requête à l'API ecoledirect (path: `url`, body: `body`, les donn
Transférée    -    Toutes , ET OUBLIE PAS DE LESe CORRIGER JUSQU’À LA FIN

2024-04-14 19:34 UTC, camarm-dev commented on docs/development/api/ed/papillon.md
> +_Il est conseillé de lire [`examples/login.ts`](examples/login.ts) pour voir une implémentation de cette double authentification_
C'est la syntaxe markdown pour mettre le texte en italique...

2024-04-14 19:35 UTC, camarm-dev commented
Merci Sacha d'avoir lu entièrement la doc, c'est un gros pavé ! Je vais résoudre les conversations une à une...

2024-04-14 19:37 UTC, Sacha338 commented on docs/development/api/ed/papillon.md
> +_Il est conseillé de lire [`examples/login.ts`](examples/login.ts) pour voir une implémentation de cette double authentification_
J'avais pas vu le deuxième. 👍

2024-04-14 19:45 UTC, camarm-dev commented on docs/development/api/ed/papillon.md
> +Désormais connectés, il vous faudra lire la [documentation des références](#références) pour comprendre et utiliser chaque fonctionnalité.
On accorde pas avec "vous" ? "Vous êtes connectés", "Désormais connecté**s**" ducoup nan ?

2024-04-28 16:34 UTC, Vilerio commented on docs/development/api/ed/papillon.md
> +Désormais connectés, il vous faudra lire la [documentation des références](#références) pour comprendre et utiliser chaque fonctionnalité.
ça dépend de si tu dis "vous" par politesse ou pour parler au pluriel

2024-04-28 16:36 UTC, camarm-dev commented on docs/development/api/ed/papillon.md
> +Désormais connectés, il vous faudra lire la [documentation des références](#références) pour comprendre et utiliser chaque fonctionnalité.
là c'est pour la politesse... pas de "s" je suppose ducoup

2024-04-28 16:36 UTC, Vilerio commented on docs/development/api/ed/papillon.md
> +Désormais connectés, il vous faudra lire la [documentation des références](#références) pour comprendre et utiliser chaque fonctionnalité.
oui je pense, mais à vérifier

2024-04-28 16:39 UTC, camarm-dev commented on docs/development/api/ed/papillon.md
> +Désormais connectés, il vous faudra lire la [documentation des références](#références) pour comprendre et utiliser chaque fonctionnalité.
> Le vous de politesse – ou vouvoiement – est un singulier. Le pronom vous-même suit cette règle.
> Madame, vous êtes invitée.
> Monsieur, vous êtes invité.

[question-orthographe.fr](https://www.question-orthographe.fr/question/conjugaison-quand-vous-est-formule-de-politesse/)

Je corrige ça de suite

2024-04-28 17:19 UTC, Sacha338 approved these changes

2024-04-28 17:20 UTC, Sacha338 commented
Donc on peut merge ?

2024-04-28 17:23 UTC, camarm-dev commented
> Donc on peut merge ?

Oui tout est bon !

2024-04-28 17:53 UTC, Vilerio approved these changes

2024-04-28 17:53 UTC, merged